# Generated by Django 5.1.1 on 2024-09-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('telefone', models.CharField(max_length=15)),
                ('confirmacao', models.BooleanField(default=False)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.profissional')),
            ],
            options={
                'unique_together': {('profissional', 'data', 'horario')},
            },
        ),
    ]
