# Generated by Django 5.1.1 on 2024-09-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_servico'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(default='servicos/sem-imagem.jpg', upload_to='servicos/'),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.servico'),
        ),
    ]
