# Generated by Django 5.1.1 on 2024-10-12 17:43

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_diafuncionamento_horariofuncionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='duracao',
            field=models.DurationField(default=datetime.timedelta(hours=1)),
        ),
    ]