# Generated by Django 5.1.1 on 2024-10-12 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_servico_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
