# Generated by Django 5.1.1 on 2024-10-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_alter_servico_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariofuncionamento',
            name='dia',
        ),
        migrations.DeleteModel(
            name='DiaFuncionamento',
        ),
        migrations.DeleteModel(
            name='HorarioFuncionamento',
        ),
    ]
