# Generated by Django 5.1.1 on 2024-10-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_remove_horariofuncionamento_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='disponibilidade',
            field=models.JSONField(default=dict),
        ),
    ]
